anguage: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install tox
script:
  - tox
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
before_script:
  - cd example
script:
  - python example.py --qt_from=pyqt --test
  - python example.py --qt_from=pyside --test

  - python example.py --qt_from=pyqt --no_dark --test
  - python example.py --qt_from=pyside --no_dark --test